import type { Metadata } from "next";

import { NextIntlClientProvider } from 'next-intl';
import { routing } from '../../i18n/routing';

import { Inter, Noto_Kufi_Arabic } from 'next/font/google';
import "../globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-en',
});

const notoKufiArabic = Noto_Kufi_Arabic({
  subsets: ['arabic'],
  variable: '--font-ar',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface LocaleLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function LocaleLayout({ children, params }: LocaleLayoutProps) {
  const { locale: rawLocale } = await params;

  const locale = rawLocale && routing.locales.includes(rawLocale as 'en' | 'ar')
    ? rawLocale
    : routing.defaultLocale;

  const messages = (await import(`../../messages/${locale}.json`)).default;
  const dir = locale === 'ar' ? 'rtl' : 'ltr';
  const fontClass = locale === 'ar' ? notoKufiArabic.className : inter.className;

  return (
    <html lang={locale} dir={dir}>
      <body className={fontClass}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar/>
          <main className="w-full">
            {children}
          </main> 
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
